### ISSUE TITLE
Job Status not persisted correctly

### ISSUE THREAD

**Issue by BeneStem** [otto-de/edison-microservice#102]
Hey there,

a refactoring included a huge bug.

https://github.com/otto-de/edison-microservice/blob/master/edison-jobs/src/main/java/de/otto/edison/jobs/service/JobService.java#L193

Previously:
```java
public void appendMessage(final String jobId, final JobMessage jobMessage) {
    // TODO: Refactor JobRepository so only a single update is required
    jobRepository.appendMessage(jobId, jobMessage);
    if (jobMessage.getLevel() == Level.ERROR) {
      jobRepository.findOne(jobId)
        .ifPresent(jobInfo -> jobRepository.createOrUpdate(jobInfo.copy().setStatus(ERROR).setLastUpdated(now(clock)).build()));
    }
  }
```

When appending any message the JobStatus was only updated when it was an `ERROR` level 
Only when using the specific skip/restart methods the status was always updated.

@MarcoGeweke1887 can you please correct this issue? :)

**Comment by MediaMarco** [comment]
Thanks for finding this, we fixed it.

**Comment by BeneStem** [comment]
No problem :) Thank you!
