### ISSUE TITLE
[edison-core] support parameter-names that have slashes to create structures

### ISSUE THREAD

**Issue by ewoelfel** [otto-de/edison-microservice#1211]
Hi,

we do have parameters that are named the following way:
`/some/service/subSection/config`

The existing setup requires application-properties to be `subSection/config` which do not represent the standard way of accessing properties with structures.

I suggest introducing a separator option helping to resolve this issue.
This way our example would result in `subSection.config`

The PR https://github.com/otto-de/edison-microservice/pull/1210 covers this

Thanks

**Comment by ftorkler** [comment]
solved by merged PR #1210
