### ISSUE TITLE
AbstractMongoRepository.byId returns matchAll equivalent Document if key is null

### ISSUE THREAD

**Issue by tschniewind** [otto-de/edison-microservice#16]
protected Document byId(final K key) {
        return key != null ? new Document(ID, key.toString()) : new Document();
    }
For example if I call `AbstractMongoRepository.delete(null)` it results in deleting the first document that would be found by matchAll, and it is not possible to delete a document with an _id=null (except it is the first document found by matchAll).

So the implementation should be changed to:
    
    protected Document byId(final K key) {
        return key != null ? new Document(ID, key.toString()) : new Document(ID, null);
    }

**Comment by gsteinacker** [comment]
Updated AbstractMongoRepository to not allow null values as key for documents. This is preventing repositories to use IDs generated by MongoDB. If you need this, we will have to write a different AbstractMongoRepository that is not returning the created documents on AbstractMongoRepository.create(..)
