### ISSUE TITLE
TestFeatureManager enableAll disables all features

### ISSUE THREAD

**Issue by davidotter1337** [otto-de/edison-microservice#193]
This look like a typo made when creating the two functions: `enableAll` and `disableAll`, they do exactly the same

```
for (FeatureState featureState : featureStates.values()) {
    featureState.setEnabled(false);
}
return this;
```

should be easy to fix by using

`featureState.enable()` in the case of `enableAll`

Location: package de.otto.edison.testsupport.togglz.TestFeatureManager

**Comment by Odkane** [comment]
Done. Easy fix. i hope it is correct

**Comment by MediaMarco** [comment]
Did you create a pull request? Or what do you mean with 'done'?

**Comment by MediaMarco** [comment]
Will be in the next release, thank you!
