### ISSUE TITLE
Provide support for MongoDB ConnectionString

### ISSUE THREAD

**Issue by deotto** [otto-de/edison-microservice#402]
We need support for MongoDB AWS_IAM role authentication. Instead of using a list of hosts a connection string should be configured. 

Required configuration example:

`edison.mongo.uriPattern=mongodb+srv://cluster0.x4oml.mongodb.net/myFirstDatabase?authSource=%24external&authMechanism=MONGODB-AWS
`

**Comment by MediaMarco** [comment]
Added in Release 2.6.5
