### ISSUE TITLE
Unable to use MongoJobRepository

### ISSUE THREAD

**Issue by JoseMejia** [otto-de/edison-microservice#54]
The Configuration Bean MongoJobsConfiguration is only active in presence of the Java Class "de.otto.edison.mongo.jobs.configuration.JobConfiguration", which is unavailable.

`
@Configuration

@ConditionalOnClass(name = "de.otto.edison.mongo.jobs.configuration.JobConfiguration")

public class MongoJobsConfiguration {...
}`

**Comment by mazzeb** [comment]
Did you include the edison-jobs library in your project? The JobConfiguration class should be included there.

**Comment by JoseMejia** [comment]
The content of the annotation @ConditionalOnClass is wrong.  I pushed already a fix

**Comment by gsteinacker** [comment]
Fixed in RC3
