### ISSUE TITLE
Provide a comment field for disabled jobs

### ISSUE THREAD

**Issue by hamvocke** [otto-de/edison-microservice#55]
Disabling jobs in Edison is easily possible using the lock icon. However, you don't see any reason why a job has been disabled. Working in a team, this means you have to find out who disabled that job and figure out the reason why it was disabled. A simple way to make this more pleasant would be to provide a comment that states why a job has been disabled. The UI could ask for that comment as soon as someone decides to disable a job and could be shown alongside the lock icon for others to see.

**Comment by gsteinacker** [comment]
The current structure of the JobRepository, having two collections and a rather questionable solution for running/disabled jobs, needs some refactoring first.

The JobRepository can be splitted into two repositories: one for Jobs, and one for different kind of locks (running, disabled, ...).
