### ISSUE TITLE
Exception with release 1.0.0.RC4

### ISSUE THREAD

**Issue by cfinckler** [otto-de/edison-microservice#58]
Since upgrading to 1.0.0.RC4 from 1.0.0.RC3 we see the following message in the exception.log:

Inconsistent constructor declaration on bean with name 'jobMutexGroups': single autowire-marked constructor flagged as optional - this constructor is effectively required since there is no default constructor to fall back to: public de.otto.edison.jobs.service.JobMutexGroups(java.util.Set)

The application seems to behave normal. So it is only a confusing message in the log.

**Comment by mazzeb** [comment]
The warning can be ignored for now and will be fixed in the next release.
