### ISSUE TITLE
edison-jobs: Group Output of single job in job overview

### ISSUE THREAD

**Issue by sroidl** [otto-de/edison-microservice#6]
In our current project we have several jobs. One of them runs fairly often (every 10 seconds or so), where as the others run only once per day. In the current job-overview page in the admin area of the edison-microservice it is very hard to see runs of those rarely running jobs, as the list is full with outputs of the one job that runs very often.

**Comment by mazzeb** [comment]
In the current release the distinct job view is enabled by default.
