### ISSUE TITLE
Add script to automagically publish releases

### ISSUE THREAD

**Issue by gsteinacker** [otto-de/edison-microservice#63]

**Comment by BeneStem** [comment]
You could use this gradle plugin for versioning: https://github.com/ethankhall/gradle-semantic-versioning
Used here by caffeine: https://github.com/ben-manes/caffeine/blob/master/build.gradle

**Comment by BeneStem** [comment]
And then travis could upload the archive for us.
See here: https://github.com/ben-manes/caffeine/blob/master/.travis.yml#L23

**Comment by BeneStem** [comment]
This could also be a nice plugin for sonatype automatic releases: https://github.com/bmuschko/gradle-nexus-plugin
I think it also releases the jars on sonatype without us clicking threw the gui...

**Comment by ben-manes** [comment]
For releasing without the gui you want
https://github.com/Codearte/gradle-nexus-staging-plugin

**Comment by BeneStem** [comment]
Hey Ben, thank you very much for your reply!
Kind of spooky that you "saw" me snooping around you repository :D
If you allow me one more question: How did you manage that? :P

**Comment by ben-manes** [comment]
GitHub search makes it easy to monitor a few keywords. I'm actually looking for usages and any api or implementation frustrations they might have. Happy to see you borrow from my scripts, too.

**Comment by BeneStem** [comment]
@ben-manes: Ahh - I see. Guess we where lucky hitting your keywords :)
Thanks again. Have a good one!
