### ISSUE TITLE
JobMarker wird in JobMessageLogAppender nicht mehr korrekt ausgewertet

### ISSUE THREAD

**Issue by peterfouquet0001** [otto-de/edison-microservice#839]
Der JobMessageLogAppender wertet nach dem Refactoring vom 06.02.2023 falsch ausgewertet.
vorher
JobMarker.JOB.contains(eventObject.getMarker())

nachher
eventObject.getMarkerList().contains(JobMarker.JOB)

Der aktuelle Code funktioniert nur, wenn als JobMarker der Marker JOB übergeben wird (final var jobMarker = JobMarker.JOB;), aber nicht wenn ein eigener Marker erstellt wird.
Siehe JobRunner
this.jobMarker = JobMarker.jobMarker(jobRunnable.getJobDefinition().jobType());

**Comment by frankbregulla1111** [comment]
@peterfouquet0001 this is fixed now with version 3.1.1

**Comment by frankbregulla1111** [comment]
fixed
