### ISSUE TITLE
Refactor de.otto.edison.metrics to use micrometer.io instead of Dropwizard metrics.

### ISSUE THREAD

**Issue by guidosteinacker1969** [otto-de/edison-microservice#98]
Spring Boot 2.0.0 is using micrometer.io for metrics. Dropwizard Metrics should not be needed anymore.
As Spring Boot does not support Dropwizard anymore, the /application/metrics do not gather data from Dropwizard metrics. The Edison example-metrics can be used to verify this behavior.

**Comment by StefanLier1986** [comment]
Edison in the version `2.0.0-m2-SNAPSHOT` now uses `micrometer` for metric publication, the dependencies and configurations for `metrics` were removed.
